dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install pydiatra $pyflakes
script:
- python test.py
- python -m pydiatra .
- pyflakes .

# vim:ts=2 sts=2 sw=2 et
